# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'evently' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for evently

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'

  target 'eventlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end