# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

install! 'cocoapods', :deterministic_uuids => false,
:integrate_targets => true

target 'evently' do
  rn_path = '../node_modules/react-native'
  
  # React pods
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

  
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # Pods for evently
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'
  
  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

pod 'lottie-ios', :path => '../node_modules/lottie-ios'

pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
pod 'CodePush', :path => '../node_modules/react-native-code-push'

#  target 'eventlyTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
